describe('template spec', () => {
  it('Cliente -Dolares negativos', () => {
    cy.visit('https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#username').type("cliente1")
    cy.get('#password_btn').type("pass123")
    cy.get('#loginForm > .btn').click()
    cy.url().should('eql', 'https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#saldoDolar').should('contain', '-1')

  })
  it('Cliente -Dolares 0', () => {
    cy.visit('https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#username').type("cliente2")
    cy.get('#password').type("pass123")
    cy.get('#loginForm > .btn').click()
    cy.url().should('eql', 'https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#saldoDolar').should('contain', '0')
  })
  it('Cliente -Dolares 0', () => {
    cy.visit('https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#username').type("cliente2")
    cy.get('#password').type("pass123")
    cy.get('#loginForm > .btn').click()
    cy.url().should('eql', 'https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#saldoDolar').should('contain', '0')
  })
  it('Cliente -Dolares Positivos', () => {
    cy.visit('https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#username').type("cliente3")
    cy.get('#password').type("pass123")
    cy.get('#loginForm > .btn').click()
    cy.url().should('eql', 'https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#saldoDolar').should('contain', '8000')
  })
  it('Cliente -Pesos 0', () => {
    cy.visit('https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#username').type("cliente3")
    cy.get('#password').type("pass123")
    cy.get('#loginForm > .btn').click()
    cy.url().should('eql', 'https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#saldoPesos').should('contain', '0')
  })
  it('Cliente -Una tarjeta', () => {
    cy.visit('https://elegionapp.azurewebsites.net/elegion/')
    cy.get('#username').type("cliente3")
    cy.get('#password').type("pass123")
    cy.get('#loginForm > .btn').click()
    cy.url().should('eql', 'https://elegionapp.azurewebsites.net/elegion/')
    cy.get('.btn-success').click()
    cy.get('.tarjeta > :nth-child(2)').should('include.text', 'VISA Crédito')
  })
})